Traceback (most recent call last):
  File "/tmp/code.py", line 45, in <module>
    force = distance**2 / k
            ~~~~~~~~^^~
OverflowError: (34, 'Numerical result out of range')
